export enum CurrencyEnum {
    USD = 'USD',
    EUR = 'EUR',
    GBP = 'GBP',
    RUB = 'RUB',
    UAH = 'UAH',
    BYN = 'BYN',
    CZK = 'CZK',
    PLN = 'PLN',
    CHF = 'CHF',
    JPY = 'JPY',
    CNY = 'CNY',
    TRY = 'TRY',
    KRW = 'KRW',
    INR = 'INR',
    BRL = 'BRL',
    MXN = 'MXN',
    ILS = 'ILS',
    KZT = 'KZT',
}
