export enum Currency {
    USD = 'USD',
    EUR = 'EUR',
    GBP = 'GBP',
    RUB = 'RUB',
    UAH = 'UAH',
    BYN = 'BYN',
    CZK = 'CZK',
    PLN = 'PLN',
    CHF = 'CHF',
    JPY = 'JPY',
    CNY = 'CNY',
    TRY = 'TRY',
    KRW = 'KRW',
    INR = 'INR',
    BRL = 'BRL',
    MXN = 'MXN',
    ILS = 'ILS',
    KZT = 'KZT',
}

export enum Countries {
    CZ = 'Czech Republic',
    DE = 'Germany',
    DK = 'Denmark',
    EE = 'Estonia',
    ES = 'Spain',
    FI = 'Finland',
    FR = 'France',
    GB = 'United Kingdom',
    GR = 'Greece',
    HR = 'Croatia',
    HU = 'Hungary',
    IE = 'Ireland',
    IT = 'Italy',
    LT = 'Lithuania',
    LU = 'Luxembourg',
    LV = 'Latvia',
    MT = 'Malta',
    NT = 'Netherlands',
    PL = 'Poland',
    PT = 'Portugal',
    RO = 'Romania',
    SE = 'Sweden',
    SI = 'Slovenia',
    SK = 'Slovakia',
    US = 'United States',
    AT = 'Austria',
    BE = 'Belgium',
    BG = 'Bulgaria',
    CY = 'Cyprus',
}
