name: lint, test, build
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        runs-on: macos-latest
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm ci
              if: always()
            - name: build production project
              run: npm run build:prod
              if: always()
            - name: typescript linting
              run: npm run lint:ts:fix
              if: always()
            - name: linting css
              run: npm run lint:scss:fix
              if: always()
            - name: unit testing
              run: npm run test:unit
              if: always()
            - name: build storybook
              run: npm run storybook:build
              if: always()
            - name: test ui 
              run: npm run test:ui:ci
              if: always()
